SELECT
	PRO.CODPROD, PRO.DESCRPROD, PRO.NCM, 'S' AS VALIDO
FROM
	TGFPRO PRO
WHERE
	PRO.NCM IS NOT NULL
	AND EXISTS(SELECT 1 FROM TGFNCM NCM
						WHERE NCM.CODNCM = PRO.NCM
           
			AND (NCM.DFIMVIGENCIA IS NULL OR NCM.DFIMVIGENCIA >= dbdate()))